version: '3'
services:
  xiaomai-bot:
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      - bot_accounts=机器人账户使用,做分割
#      - default_account=默认机器人账户
#      - Master=机器人管理账户
#      - mirai_host=mirai服务器
#      - verify_key=mah验证token
#      - test_group=debug群组
#      - db_link=sqlite位置
    container_name: xiaomai-bot
    restart: always
    volumes:
      - /xiaomai-bot/config/config.yaml:/xiaomai-bot/config.yaml                                    # 配置文件
      - /xiaomai-bot/config/data.db:/xiaomai-bot/data.db                                            # 数据库文件
      - /xiaomai-bot/data/battlefield:/xiaomai-bot/data/battlefield/                                # 战地一机器人资源
      - /xiaomai-bot/imgs/random_picture:/xiaomai-bot/modules/self_contained/random_picture/imgs/   # 随机图片资源
      - /xiaomai-bot/imgs/random_wife:/xiaomai-bot/modules/self_contained/random_wife/imgs/         # 随机老婆图片资源
      - /xiaomai-bot/imgs/random_dragon:/xiaomai-bot/modules/self_contained/random_dragon/imgs/     # 随机龙图图片资源
    network_mode: host