name: Docker Image CI/CD

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./
      - name: Login to Ali Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
      - name: Login to Ali Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        run: |
          docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_REPOSITORY }} -q)
          docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}:latest -q)
          docker rmi -f $(docker images ${{ secrets.DOCKER_REPOSITORY }}:latest -q)
          docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
          docker run -d ${{ secrets.DOCKER_REPOSITORY }}:latest
