name: Update Repo Diagram

on:
  workflow_dispatch: {}            # 手动触发
  push:                            # 每次推送时触发
    branches:
      - v3
  pull_request:                    # PR 合并后触发
    types: [closed]
    branches:
      - v3
  schedule:                        # 每周日 00:00 自动运行，但需检查分支是否有变动
    - cron: "0 0 * * 0"

jobs:
  update-diagram:
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if v3 branch has commits in the last 7 days
        id: check_changes
        run: |
          RECENT_COMMITS=$(git log --since="7 days ago" --oneline | wc -l)
          if [ "$RECENT_COMMITS" -eq 0 ]; then
            echo "No recent commits, skipping workflow."
            exit 1
          fi

      - name: Update repository structure diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
